Feature/vg 264 client uat media manager
PortableStudios/fila-cms pull request #128
Opened 2024-06-07 05:29 UTC by jeric-portable

2024-06-10 09:15 UTC, kyoungportable requested changes

2024-06-13 07:16 UTC, jeric-portable commented on src/Livewire/MediaLibraryTable.php
> +                    ->multiple()
used repeater to attach alt text to specific file upload

2024-06-13 10:55 UTC, kyoungportable approved these changes

2024-06-13 11:07 UTC, jny986 approved these changes

2024-06-13 11:31 UTC, merged