Feature/filacms 5 create abstract content resource
PortableStudios/fila-cms pull request #5
Opened 2024-02-12 03:25 UTC by jeremy-portable

- Implemented Abstract Content Resource
- Extended it as Page model
- Implemented Resource for the page model
- Implemented Tiptap Editor
- Added Revisionable to track revisions
- Added feature to revert specific revisions

2024-02-12 05:17 UTC, kyoungportable requested changes

2024-02-12 05:17 UTC, kyoungportable commented on src/Events/ContentCreating.php
> +        $page->updated_user_id = auth()->user()->id;
Can we make sure we're only doing this if the slug is blank?  The user should potentially be able to override the slug.

2024-02-12 05:17 UTC, kyoungportable commented on src/Filament/Resources/PageResource.php
> +<?php
Suggest we make all of these `abstract`, e.g `src/Filament/Resources/AbstractContentResource.php` etc.  Then create `src/Filament/Resources/PageResource.php` extending `AbstractContentResource`, not just `Resource`.

2024-02-12 05:17 UTC, kyoungportable commented on database/migrations/2024_02_09_400000_create_contents_table.php
> +    {
Table name here should be 'pages', as the concrete implementation is pages.

2024-02-12 05:17 UTC, kyoungportable commented on src/Commands/InstallCommand.php
> +        $this->call('make:-filament theme');
Is the '-' meant to be there?

2024-02-13 02:22 UTC, jeremy-portable commented on src/Commands/InstallCommand.php
> +        $this->call('make:-filament theme');
Yup sorry

2024-02-21 07:40 UTC, kyoungportable approved these changes

2024-02-21 07:40 UTC, merged